apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apimanager-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apimanager
    spec:
      containers:
      - name: apimanager-pod
        image: gabo10096/apimanager:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: apimanager
  labels:
    app: apimanager-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: apimanager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderservice-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice-pod
        image: gabo10096/orderservice:latest
        ports:
        - containerPort: 8200
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productservice-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice-pod
        image: gabo10096/productservice:latest
        ports:
        - containerPort: 8300
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userservice-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice-pod
        image: gabo10096/userservice:latest
        ports:
        - containerPort: 8100